-- Migration 005: (removido)
-- A antiga tabela `members` foi incorporada em `growth_group_participants` na Migration 004.
-- Este arquivo permanece apenas para preservar a ordem das migrações históricas.
