-- Migration 015: Disable RLS for tests
-- This migration should only be applied in a testing environment.

ALTER TABLE people DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE growth_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE growth_group_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE meetings DISABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_member_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE visitors DISABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_visitor_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_series DISABLE ROW LEVEL SECURITY;
ALTER TABLE lessons DISABLE ROW LEVEL SECURITY;
